kidschores/chores/urls.py
from django.urls import path
from . import views


app_name = 'chores'

urlpatterns = [
    path('', views.home, name='home'),
    path('chore_list/', views.chore_list, name='chore_list'),
    path('register/', views.register, name='register'),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name='login'),
    path("edit_chore/<int:chores_id>/", views.edit_chore, name="edit_chore"),
    path("new_chore/", views.new_chore, name="new_chore"),
    path("pending_chores/", views.pending_chores, name='pending_chores'),
    path("approve_chores/<int:chores_id>/", views.approve_chores, name='approve_chores'),
    path("profile/", views.profile, name="profile"),
    path("index/", views.index, name="index"),
]

kidschores/kidschores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chores.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

kidschores/chores/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.conf import settings


class Chores(models.Model):
    name = models.CharField(max_length=140)
    time_listed = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateTimeField()
    pay = models.FloatField()
    image = models.ImageField(blank=True, upload_to='images/')
    completed = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.FloatField(default=0.00)
        
    def __str__(self):
        return f'{self.user.username} Profile'

    def deposit(self, amount):
        self.balance += amount
        self.save()

    def withdraw(self, amount):
        self.balance -= amount
        self.save()

kidschores/chores/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import Chores

class DateInput(forms.DateInput):
    input_type = 'date'

class ChoreForm(forms.ModelForm):


    class Meta:
        model = Chores
        fields = ['name', 'expire_date', 'pay']
        labels = {'text': ''}
        widgets = {'expire_date': DateInput()}

class CompleteForm(forms.ModelForm):
    class Meta:
        model = Chores
        fields = ['completed', 'image']

class ApproveForm(forms.ModelForm):
    class Meta:
        model = Chores
        fields = ['approved']

kidschores/chores/views.py
from django.shortcuts import render, redirect
from .models import Chores, Profile
from .forms import ChoreForm, CompleteForm, ApproveForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.


def home(request):
    return render(request, 'chores/home.html')

    # TODO: Filter Objects by expired
def chore_list(request):
    """Show list of chores"""
    
    chores = Chores.objects.order_by('name').exclude(completed=True)

    context = {'chores' : chores}
    return render(request, 'chores/chore_list.html', context)

def new_chore(request):
    """admin user creates new available chore"""
    if request.method != 'POST':
        # Create blank form
        form = ChoreForm()
    else:
        # Post data submitted, process data
        form = ChoreForm(data=request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('chores:chore_list'))

    context ={'form' : form}
    return render(request, 'chores/new_chore.html', context)

@login_required
def edit_chore(request, chores_id):
    """User edits available chore"""
    chore = Chores.objects.get(id=chores_id)
    exp = chore.expire_date
    pay = chore.pay
    
    if request.user.get_username() == 'admin':
        if request.method != "POST":
            # Initial request, prefill form with current chore
            form = ChoreForm(instance=chore)
        else:
            # POST data submitted; process data
            form = ChoreForm(instance=chore, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('chores:chore_list'))
    else:
        if request.method != "POST":
            # Initial request, prefill form with current chore
            form = CompleteForm(instance=chore)
        else:
            # POST data submitted; process data
            form = CompleteForm(instance=chore, data=request.POST, files=request.FILES)
            if form.is_valid():
                new = form.save(commit=False)
                new.image = request.FILES.get('image')
                new.owner = request.user
                new.save()
                #form.save()
                return HttpResponseRedirect(reverse('chores:chore_list'))

    context = {'chore': chore, 'form':form, 'exp' : exp, 'pay' : pay}
    return render(request, 'chores/edit_chore.html', context)


def pending_chores(request):
    """list pending chores waitning for approval"""
    chores = Chores.objects.order_by('name').filter(completed=True).exclude(approved=True)
    
    context = {'chores' : chores}
    return render(request, 'chores/pending_chores.html', context)

def approve_chores(request, chores_id):
    chore = Chores.objects.get(id=chores_id)
    pay = chore.pay
    

    if request.method != "POST":
            # Initial request, prefill form with current chore
        form = ApproveForm(instance=chore)
    else:
            # POST data submitted; process data
        form = ApproveForm(instance=chore, data=request.POST)
        if form.is_valid():
            approval = form.save(commit=False)
            chore.owner.profile.deposit(pay)
            approval.save()
            return HttpResponseRedirect(reverse('chores:pending_chores'))

    context = {'chore':chore, 'form':form}
    return render(request, 'chores/approve_chore.html', context)

@login_required
def profile(request):

    return render(request, 'chores/profile.html')
    

# -------Below is User Views, Login, Logout, Register --------

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
            return redirect("chores:home")
        
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request = request,
                        template_name = "chores/register.html",
                        context={"form":form}
            )

    form = UserCreationForm        
    return render(request = request,
                template_name = "chores/register.html",
                context={"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "logged out successfully!")
    return redirect("chores:home")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")

    form = AuthenticationForm()
    return render(request = request,
                template_name = "chores/login.html",
                context={"form":form})



#below is for index.html reference for styling

def index(request):
    return render(request, 'chores/index.html')

kidschores/chores/templates/chores/approve_chore.html
{% extends 'chores/base.html' %}

{% load crispy_forms_tags %}

{% block content %}



<div>


    <br>
    <br>
    <br>
    <br>


    <div class="card card-cascade wider">
        <div class="view view-cascade overlay">
            <img class="card-img-top" src="{{chore.image.url}}" alt="Card image cap">
            <a>
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>
        <div class="card-body card-body-cascade text-center">

            <!-- Title -->
            <h4 class="card-title"><strong>{{chore.owner}} has a balance of {{chore.owner.profile.balance}}</strong>
            </h4>
            <!-- Subtitle -->
            <h5 class="blue-text pb-2"><strong>This chore is worth {{chore.pay}}</strong></h5>

        </div>
    </div>

</div>

<form class="text-center border border-light p-5" action="{% url 'chores:approve_chores' chore.id %}" method="POST">
    <p class="h4 mb-4">Approve Chore</p>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info btn-block my-4" type="submit">Save</button>
</form>

{% endblock %}

kidschores/chores/templates/chores/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'https://use.fontawesome.com/releases/v5.8.2/css/all.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        @media (min-width: 800px) and (max-width: 850px) {
            .navbar:not(.top-nav-collapse) {
                background: #1C2331 !important;
            }
        }
    </style>
</head>

<body>

    <!-- Start your project here-->

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand" href="#">
                <strong>Chore</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'chores:home' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chores:chore_list' %}">Chore List</a>
                    </li>

                    <!--if authenticated-->
                    {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chores:logout' %}">Logout
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chores:profile' %}">Profile
                        </a>
                    </li>


            </div>
            <!--if not logged in-->
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'chores:login' %}">Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chores:register' %}">Register
                </a>
            </li>

            {% endif %}
            </ul>






        </div>

        </div>
    </nav>
    <!-- Navbar -->



    <div class="container">
        {% block content %}

        {% endblock %}
    </div>


    <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();

    </script>
</body>

</html>

kidschores/chores/templates/chores/chore_list.html
{% extends 'chores/base.html' %}


<div class="container-fluid">
    <br>
    <p>
        <br>
        {% block content %}
        <br>
        <br>
        <br>
        <h1 class="text-center">Available Chores</h1>
        <br>
        {% for chore in chores %}

        <div class="list-group">
            <a href="{% url 'chores:edit_chore' chore.id %}"
                class="text-sm-center list-group-item list-group-item-action active">
                {{ chore }}
            </a>
        </div>
        {% empty %}
        <li>
            No chores available
        </li>
        {% endfor %}

        {% endblock %}

    </p>

</div>

kidschores/chores/templates/chores/edit_chore.html
{% extends 'chores/base.html' %}
{% load crispy_forms_tags %}


{% block content %}


<br>
<br>

<form class="text-center border border-light p-5" action="{% url 'chores:edit_chore' chore.id %}" method="post"
    enctype="multipart/form-data">
    <p class="h4 mb-4">Complete Chore</p>
    <p class="h4 mb-4">Chore : {{ chore }}</p>
    <p class="h4 mb-4">This chore is worth ${{pay}}</p>
    <p class="h4 mb-4">This chore needs to be completed by {{exp}}</p>


    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Edit Chore</legend>
        {{ form|crispy }}
    </fieldset>

    <div class="form-group">
        <button class="btn btn-info btn-block my-4" type="submit">Submit</button>
    </div>
</form>

{% endblock %}

kidschores/chores/templates/chores/home.html
{% extends 'chores/base.html' %}


{% block content %}

<br>
<br>
<br>
{% if user.is_authenticated %}
<div class="row justify-content-end">
    <div class="col-4">
        <strong>Hi {{user.username}}</strong>
    </div>
</div>
{% endif %}
<!-- Section: Features v.2 -->
<div class="text-center border border-light p-5">
    <section class="my-6">

        {% if request.user.is_superuser  %}
        <!-- Section heading -->
        <h2 class="h1-responsive font-weight-bold text-center my-5">Admin Options</h2>
        <!-- Section description -->
        <p class="lead grey-text text-center w-responsive mx-auto mb-5">Lorem ipsum</p>

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-5">

                <!-- Grid row -->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-2 col-md-3 col-2">
                        <i class="fas fa-bullhorn blue-text fa-2x"></i>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-lg-10 col-md-9 col-10">
                        <h4 class="font-weight-bold">New Chore</h4>
                        <p class="grey-text">Create a new chore here</p>
                        <button type="button" class="btn btn-primary"
                            onclick=window.location.href="{% url 'chores:new_chore' %}">New Chore</button>
                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row -->

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-5">

                <!-- Grid row -->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-2 col-md-3 col-2">
                        <i class="fas fa-cogs pink-text fa-2x"></i>
                    </div>
                    <!-- Grid column -->
                    <div class="col-lg-10 col-md-9 col-10">
                        <h4 class="font-weight-bold">Pending Chores</h4>
                        <p class="grey-text">View and approve pending chores</p>
                        <button type="button" class="btn btn-primary"
                            onclick=window.location.href="{% url 'chores:pending_chores' %}">Pending
                            Chores</button>
                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row -->
            </div>
        </div>
        <!-- Grid column -->
        {% else %}
        <!-- Grid column -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-5">

                <!-- Grid row -->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-2 col-md-3 col-2">
                        <i class="fas fa-bullhorn blue-text fa-2x"></i>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-lg-10 col-md-9 col-10">
                        <h4 class="font-weight-bold">Profile</h4>
                        <p class="grey-text">View Profile and Balance</p>
                        <button type="button" class="btn btn-primary"
                            onclick=window.location.href="{% url 'chores:profile' %}">Profile</button>
                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row -->

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 mb-md-0 mb-5">

                <!-- Grid row -->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-2 col-md-3 col-2">
                        <i class="fas fa-cogs pink-text fa-2x"></i>
                    </div>
                    <!-- Grid column -->
                    <div class="col-lg-10 col-md-9 col-10">
                        <h4 class="font-weight-bold">Available Chores</h4>
                        <p class="grey-text">View and Complete Available Chores</p>
                        <button type="button" class="btn btn-primary"
                            onclick=window.location.href="{% url 'chores:chore_list' %}">Chores
                            Chores</button>
                    </div>
                    <!-- Grid column -->

                </div>
                {% endif %}
            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->
</div>
</section>
<!-- Section: Features v.2 -->


{% endblock %}

kidschores/chores/templates/chores/login.html
{% extends 'chores/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
<!-- Default form login -->

<div class="container">
    <form class="text-center border border-light p-5" method="POST">
        <p class="h4 mb-4">Sign in</p>
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-info btn-block my-4" type="submit">Sign in</button>
        Don't have an account? <a href="/register" target="blank"><strong>Register</strong></a>

    </form>
</div>


{% endblock %}

kidschores/chores/templates/chores/new_chore.html
{% extends 'chores/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<br>
<br>
<br>
<br>


<form class="text-center border border-light p-5" action="{% url 'chores:new_chore' %}" method="post">
    <p class="h4 mb-4">New Chore</p>
    {% csrf_token %}
    {{ form|crispy}}
    <button class="btn btn-info btn-block my-4" type="submit">Save</button>

</form>


{% endblock %}

kidschores/chores/templates/chores/pending_chores.html
{% extends 'chores/base.html' %}


{% block content %}
<br>
<br>
<br>
<div>
    <h1 class="text-center">Approve Chores</h1>

    {% for chore in chores %}
    <div class="list-group">
        <a href="{% url 'chores:approve_chores' chore.id %}"
            class="text-sm-center list-group-item list-group-item-action active">
            {{ chore }}
        </a>
        {% empty %}
        <li>
            <p>no pending chores</p>
        </li>
        {% endfor %}

    </div>
    {% endblock %}

kidschores/chores/templates/chores/profile.html
{% extends 'chores/base.html' %}


{% block content %}

<br><br><br>
<p class="h4 mb-4 text-center">{{user}}'s Balance is ${{user.profile.balance}}</p>


{% endblock %}

kidschores/chores/templates/chores/register.html
{% extends 'chores/base.html' %}

{% load crispy_forms_tags %}

<div class="container">
    {% block content %}

    <br>
    <br>

    <form class="text-center border border-light p-5" method="POST">
        <p class="h4 mb-4">Sign Up</p>
        {% csrf_token %}
        {{form|crispy}}

        <button class="btn btn-info btn-block my-4" type="submit">Sign Up</button>


        Already have an account? <a href="/login" target="blank"><strong>Login</strong></a>

    </form>


    {% endblock %}
</div>